### ISSUE TITLE
saying things to villagers errors

### ISSUE THREAD

**Issue by playr-lol** [Ranzeplay/saysth#4]
also prefix doesn't appear in config
```
[18:49:26] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.IllegalArgumentException: bound must be greater than origin
        at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:236) ~[?:?]
        at java.base/java.util.random.RandomGenerator.nextInt(RandomGenerator.java:678) ~[?:?]
        at space.ranzeplay.saysth.villager.VillagerManager.generateRandomVillagerMemory(VillagerManager.java:29) ~[saysth-fabric-0.2.jar:?]
        at space.ranzeplay.saysth.villager.VillagerManager.getVillager(VillagerManager.java:43) ~[saysth-fabric-0.2.jar:?]
        at space.ranzeplay.saysth.events.PlayerChatEvent.onPlayerChat(PlayerChatEvent.java:24) ~[saysth-fabric-0.2.jar:?]
        at space.ranzeplay.saysth.fabric.ChatListener.onChatMessage(ChatListener.java:15) ~[saysth-fabric-0.2.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:103) ~[fabric-message-api-v1-6.0.13+6573ed8cd1-914a860d59608ef1.jar:?]
        at net.minecraft.class_3324.handler$bmh000$fabric-message-api-v1$onSendChatMessage(class_3324.java:5022) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1456) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1299) ~[server-intermediary.jar:?]
        at net.minecraft.class_7619.method_44903(class_7619.java:30) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Ranzeplay** [comment]
Are you upgrading from v0.2 to v0.3 or just using v0.3 at the beginning?
If upgrading, please manually add the new configuration. But the config will be fixed automatically in the next version.

**Comment by Ranzeplay** [comment]
Or have you added any villager personalities or name candidates?

**Comment by playr-lol** [comment]
haven't added any personalites or name canidates, haven't upgraded

**Comment by playr-lol** [comment]
Wait i'm stupid hold on (also can u put like default personalities and name canidates cuz i literally have NO IDEA of any)

**Comment by Ranzeplay** [comment]
Okay, I'll do it in the next version.
Maybe generating some using LLMs? Such as ChatGPT, Perplexity.
